# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [AppBundle]
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: false
    assets:

        ############################################################################################################
        # FRONTEND ASSETS
        ############################################################################################################
        frontend_lesses:
            inputs:
                - @AppBundle/Resources/public/less/main.less
            filters: lessphp
        frontend_stylesheets:
            inputs:
                - assets/mobile-angular-ui-1.2.0-beta.11/dist/css/mobile-angular-ui-base.min.css
                #- assets/mobile-angular-ui-1.2.0-beta.11/dist/css/mobile-angular-ui-hover.min.css
                #- assets/mobile-angular-ui-1.2.0-beta.11/dist/css/mobile-angular-ui-desktop.min.css

                - assets/angular-growl/angular-growl-2-master/build/angular-growl.min.css
                - assets/ngProgress/ngProgress.css
                - assets/bootstrap-3.3.2/css/bootstrap.min.css
                - assets/bootstrap-3.3.2/css/bootstrap-theme.min.css

                - @frontend_lesses
            filters: [?minifier_css, cssrewrite]

        # header javascript
        frontend_header_javascripts_cssrewrite:
            inputs: []
            filters: [cssrewrite]
        frontend_header_javascripts:
            inputs:
                - assets/AngularJS/1.4.0-beta.1/angular.min.js
                #- assets/AngularJS/1.4.0-beta.1/angular-route.js
                #- assets/AngularJS/1.2.0/angular.js
                #- assets/AngularJS/1.2.0/angular-route.js
            filters: [?minifier_js]

        # footer javascript
        frontend_foooter_javascripts_cssrewrite:
            inputs: []
            filters: [cssrewrite]
        frontend_footer_javascripts:
            inputs:

                - assets/mobile-angular-ui-1.2.0-beta.11/dist/js/mobile-angular-ui.min.js
                #- assets/mobile-angular-ui-1.2.0-beta.11/dist/js/mobile-angular-ui.core.min.js
                #- assets/mobile-angular-ui-1.2.0-beta.11/dist/js/mobile-angular-ui.components.min.js
                - assets/mobile-angular-ui-1.2.0-beta.11/dist/js/mobile-angular-ui.gestures.min.js

                - assets/underscorejs/underscore-min.js

                - assets/jquery-1.11.2/jquery-1.11.2.min.js
                - assets/jquery-1.11.2/jquery-migrate-1.2.1.min.js
                - assets/lazyload/jquery.lazyload.min.js

                - assets/bootstrap-3.3.2/js/bootstrap.min.js
                - assets/js-marker-clusterer/markerclusterer_compiled.js
                - assets/RainbowVis-JS/rainbowvis.js
                - assets/ui-bootstrap/ui-bootstrap-tpls-0.12.0.js
                - assets/angular-growl/angular-growl-2-master/build/angular-growl.min.js

                - assets/ngProgress/ngProgress.min.js
                - assets/spinjs/spin.min.js
                - assets/angular-spinner-0.6.1/angular-spinner.min.js
                - assets/RainbowVis-JS/rainbowvis.js
                - %kernel.root_dir%/../web/bundles/fosjsrouting/js/router.js

                - @AppBundle/Resources/public/js/main.js

                - @AppBundle/Resources/public/js/angularjs/app.js
                - @AppBundle/Resources/public/js/angularjs/filters.js
                - @AppBundle/Resources/public/js/angularjs/services/*.js
                - @AppBundle/Resources/public/js/angularjs/controllers.js

            filters: [?minifier_js]
