<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TwitterAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterAccountRepository extends EntityRepository
{
}
